#!/bin/bash

data=$(head -n $LSB_JOBINDEX $1 | tail -n1)

## The input file ($1) contains two fields per line ($data):
##	- the path to the possorted genome bam files generated by cellranger for each 10x sample
##	- the corresponding pool of the 10x sample 

INPUTBAM=$(echo $data | awk {'print $1'} )
DEMUXLET=/software/demuxlet/demuxlet
rootfolder=$(echo $INPUTBAM | sed 's/possorted_genome_bam.bam//g')


##Input vcf with the genotypes from all the donors of the Hipsci project
VCFDIR=/projects/NeuroSeq/demuxlet/wec_filtered_vcf/hg19
INPUTVCF=${VCFDIR}/hipsci.wec.gtarray.HumanCoreExome.imputed_phased.20180102.genotypes.gnomadMAF0.05.biallelic.ALLchr.hg19.inputdemuxlet.vcf

## Barcodes per 10x sample
INPUTBARCODES=$(echo ${rootfolder}filtered_feature_bc_matrix/barcodes.tsv.gz)

## Output file per 10x sample
OUTPUT=$(echo ${rootfolder}output.demuxlet.doublet0.5)

## Corresponding pool per 10x sample
poolnum=$(echo $data | awk {'print $2'})

## Samples present in the pool
SAMPLELIST=demuxlet/deconvolution/${poolnum}_sample_list.txt

## Run demuxlet
$DEMUXLET --sam $INPUTBAM --vcf $INPUTVCF --doublet-prior 0.5 --group-list $INPUTBARCODES --out $OUTPUT --sm-list $SAMPLELIST

